### ISSUE TITLE
I want to add my self In gitfetch.js file and I Want to Contribute for the projects.

### ISSUE THREAD

**Issue by Bharath-KumarReddy** [Boltjazz/Hacktober23#15]
I want to add my self in gitfetch.js and I Want  to Contribute for the Projects .

Please consider this under Hacktoberfest_23 : )

**Comment by Boltjazz** [comment]
try to do the questions in task 2 which will be challenging for you , try and learn

**Comment by Bharath-KumarReddy** [comment]
Sure I will definitely Solve and Learn them : )
