### ISSUE TITLE
can I be assigned the python data structures?

### ISSUE THREAD

**Issue by dfordp** [Boltjazz/Hacktober23#25]
can I be assigned the python data structures?

**Comment by Boltjazz** [comment]
sure

**Comment by testingdoonly** [comment]
I would like to take up this issue,
please assign me with this @Boltjazz

**Comment by dfordp** [comment]
The task has been completed by me you can take up some other issue

**Comment by testingdoonly** [comment]
> The task has been completed by me you can take up some other issue

okay

**Comment by testingdoonly** [comment]
@Boltjazz can merge and add the hacktoberfest label to this
PR #49
