### ISSUE TITLE
Phonebook Design

### ISSUE THREAD

**Issue by Boltjazz** [Boltjazz/Hacktober23#28]
The "Phonebook" project involves creating a digital phonebook application that allows users to manage and organize their contacts efficiently. This project aims to provide a user-friendly and feature-rich phonebook solution, making it easy for users to store, retrieve, and update their contact information in any language

**Comment by deexithparand** [comment]
Hi @Boltjazz, I'd like to work on this issue. Could you please assign it to me.

**Comment by itssiddhantjain** [comment]
Hello @Boltjazz, please assign this issue to me as i already worked on this kind of problem in past and has a great experience.

**Comment by deexithparand** [comment]
Hey @Boltjazz I've already started working on this issue, since you've assigned it to me. May I know the reason for the closure of this issue.
